"""AIG Cockpit Dashboard v2 — multi-tab self-contained HTML.

Tabs:
  1. Overview      — Goals, Sprint, CEO, Routines, Audit, Signal Pipeline,
                     Countdown timers, Decision Log, Circuit Breakers
  2. Markets       — US / UAE / Crypto cards with metrics + winners/losers
  3. Agents        — 27-agent directory by v7.0 layer
  4. KPIs          — 14-KPI scorecard
  5. Live Status   — Connection health: TV MCP, Telegram, GitHub, yfinance, Engine
  6. Paper P&L     — NAV chart + per-position cards from paper_forward_positions.json
  7. Risk          — VIX gauge, drawdown, correlation
  8. Telegram      — Recent send log
  9. Commits       — Git commit timeline
 10. History       — Sessions with search/filter
 11. Glossary      — Term definitions
 12. CEO           — Decision log with search

Header features:
  - NAV, Mode pill
  - Alert bell with unread count (sprint blockers + fails)
  - Global search (filters visible elements across active tab)

All data injected server-side from current state. Regenerated by every
Cloud Routine. Self-contained — no external CDN deps.
"""
from __future__ import annotations
import html
import json
import os
import re
import subprocess
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DASHBOARD_PATH = ROOT / "dashboard.html"
UNIVERSE_DIR = ROOT / "universe"
HOME = Path(os.path.expanduser("~"))
SCHEDULED_TASKS_DIR = HOME / ".claude" / "scheduled-tasks"
TELEGRAM_DIR = HOME / ".claude" / "channels" / "telegram"
TELEGRAM_LOG = ROOT / "telegram_sent_log.json"
PAPER_STATE = ROOT / "paper_forward_positions.json"
GST = timezone(timedelta(hours=4))

# ---- helpers --------------------------------------------------------------

def esc(x) -> str:
    return html.escape(str(x), quote=True)


def _safe_read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _count_universe(path: Path) -> int:
    if not path.exists():
        return 0
    n = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            n += 1
    return n


def _git_log(n: int = 30) -> list[dict]:
    try:
        out = subprocess.check_output(
            ["git", "log", f"-{n}", "--pretty=format:%h|%H|%ad|%ae|%s",
             "--date=iso-strict"],
            cwd=str(ROOT), text=True, stderr=subprocess.DEVNULL
        )
    except Exception:
        return []
    rows = []
    for line in out.splitlines():
        parts = line.split("|", 4)
        if len(parts) == 5:
            rows.append({"sha": parts[0], "full_sha": parts[1],
                         "date": parts[2], "email": parts[3],
                         "subject": parts[4]})
    return rows


def _git_remote_url() -> str:
    try:
        url = subprocess.check_output(
            ["git", "config", "--get", "remote.origin.url"],
            cwd=str(ROOT), text=True, stderr=subprocess.DEVNULL
        ).strip()
        if url.endswith(".git"):
            url = url[:-4]
        return url
    except Exception:
        return ""


def _scheduled_tasks() -> list[dict]:
    rows = []
    if not SCHEDULED_TASKS_DIR.exists():
        return rows
    for d in sorted(SCHEDULED_TASKS_DIR.iterdir()):
        if not d.is_dir():
            continue
        skill = d / "SKILL.md"
        if not skill.exists():
            continue
        head = skill.read_text(encoding="utf-8", errors="ignore").splitlines()[:30]
        fm: dict[str, str] = {}
        in_fm = False
        for line in head:
            if line.strip() == "---":
                in_fm = not in_fm
                continue
            if in_fm:
                m = re.match(r"^([\w-]+):\s*(.*)$", line)
                if m:
                    fm[m.group(1)] = m.group(2).strip().strip('"')
        rows.append({"name": d.name, "cron": fm.get("cron", fm.get("schedule", "—")),
                     "description": fm.get("description", ""),
                     "enabled": fm.get("enabled", "true")})
    return rows


def _telegram_status() -> dict:
    status = {"bot_pid": None, "alive": False, "policy": None,
              "allowFrom": [], "last_log_mtime": None}
    pid_file = TELEGRAM_DIR / "bot.pid"
    if pid_file.exists():
        try:
            pid = int(pid_file.read_text().strip())
            status["bot_pid"] = pid
            if os.name == "nt":
                import subprocess as sp
                r = sp.run(["tasklist", "/FI", f"PID eq {pid}", "/FO", "CSV"],
                          capture_output=True, text=True)
                status["alive"] = "bun" in r.stdout.lower()
        except Exception:
            pass
    access_file = TELEGRAM_DIR / "access.json"
    if access_file.exists():
        try:
            j = json.loads(access_file.read_text(encoding="utf-8"))
            status["policy"] = j.get("dmPolicy")
            status["allowFrom"] = j.get("allowFrom", [])
        except Exception:
            pass
    log = TELEGRAM_DIR / "server.log"
    if log.exists():
        status["last_log_mtime"] = datetime.fromtimestamp(
            log.stat().st_mtime, tz=GST
        ).strftime("%Y-%m-%d %H:%M GST")
    return status


def _telegram_sent_log() -> list[dict]:
    if not TELEGRAM_LOG.exists():
        return []
    try:
        return json.loads(TELEGRAM_LOG.read_text(encoding="utf-8"))
    except Exception:
        return []


def _latest_validation_results() -> dict:
    results: dict[tuple[str, str], tuple[float, Path, dict]] = {}
    for p in ROOT.glob("validation_*.json"):
        d = _safe_read_json(p)
        if not d or not d.get("portfolio"):
            continue
        args = d.get("args", {})
        strat = args.get("strategy", "?")
        uni = (args.get("universe") or "").lower()
        if "uae" in p.name or "uae" in uni:
            market = "UAE"
        elif "crypto" in p.name or "crypto" in uni:
            market = "CRYPTO"
        else:
            market = "US"
        key = (strat, market)
        mt = p.stat().st_mtime
        if key not in results or mt > results[key][0]:
            results[key] = (mt, p, d)
    out = {}
    for (strat, market), (mt, p, d) in results.items():
        pf = d["portfolio"]
        out[(strat, market)] = {
            "file": p.name,
            "mtime": datetime.fromtimestamp(mt, tz=GST).strftime("%Y-%m-%d %H:%M"),
            "verdict": pf.get("verdict"),
            "passed": bool(pf.get("passed")),
            "trades": pf.get("portfolio_trades"),
            "contributors": pf.get("contributing_tickers"),
            "universe_size": pf.get("universe_size"),
            "expectancy": pf.get("portfolio_expectancy"),
            "win_rate": pf.get("portfolio_win_rate"),
            "sharpe_raw": pf.get("portfolio_sharpe_raw"),
            "sharpe_def": pf.get("portfolio_sharpe_deflated"),
            "reasons": pf.get("reasons") or [],
        }
    return out


def _ceo_brain_sections() -> dict:
    p = ROOT / "ceo_brain.md"
    if not p.exists():
        return {"sprint_tracker": [], "decisions": [], "open_issues": [],
                "raw": ""}
    text = p.read_text(encoding="utf-8", errors="ignore")
    # parse sprint tracker rows
    sprint = []
    in_tracker = False
    for line in text.splitlines():
        if line.strip().startswith("## SPRINT TRACKER"):
            in_tracker = True
            continue
        if in_tracker and line.startswith("## "):
            break
        if in_tracker and line.startswith("| ") and not line.startswith("| #") and not line.startswith("|---"):
            parts = [p.strip() for p in line.split("|")[1:-1]]
            if len(parts) >= 5 and parts[0].strip().isdigit():
                sprint.append({
                    "id": parts[0], "item": parts[1], "status": parts[2],
                    "criteria": parts[3], "notes": parts[4],
                })
    # decisions
    decisions = []
    for m in re.finditer(
        r"^\d+\.\s+\*\*(\d{4}-\d{2}-\d{2}\s+D-\d+)\*\*\s+—\s+\*([^*]+)\*\s*\n([^\n]*)",
        text, flags=re.M):
        decisions.append({
            "id_date": m.group(1).strip(),
            "title": m.group(2).strip(),
            "rationale_head": m.group(3).strip(),
        })
    # open issues (just first lines of the OPEN ISSUES section if present)
    open_issues = []
    m = re.search(r"^##+\s+OPEN ISSUES.*?$", text, flags=re.M)
    if m:
        rest = text[m.end():]
        end = re.search(r"^##+ ", rest, flags=re.M)
        block = rest[:end.start()] if end else rest
        for line in block.splitlines():
            if line.strip().startswith(("###", "1.", "2.", "3.", "- ", "* ")):
                open_issues.append(line.strip())
    return {"sprint_tracker": sprint, "decisions": decisions,
            "open_issues": open_issues, "raw": text}


def _auditor_findings() -> list[dict]:
    p = ROOT / "auditor_report.md"
    if not p.exists():
        return []
    text = p.read_text(encoding="utf-8", errors="ignore")
    findings = []
    for m in re.finditer(
        r"^###\s+(\d+)\.\s+(BLOCKING|WARNING|NOTE)\s+—\s+(.+?)$",
        text, flags=re.M):
        findings.append({"id": m.group(1), "severity": m.group(2),
                         "title": m.group(3).strip()})
    return findings


def _paper_state() -> dict | None:
    return _safe_read_json(PAPER_STATE)


def _cron_next_fire_gst(cron: str) -> str:
    """Best-effort next-fire calculation for the simple cron expressions we use.
    Returns a human-readable string in GST."""
    try:
        parts = cron.strip().split()
        if len(parts) != 5:
            return "—"
        minute, hour, dom, month, dow = parts
        now = datetime.now(GST)
        # iterate forward minute-by-minute up to 8 days (covers monthly easily
        # for our cron set; if month/dom restricts further, this still hits)
        for i in range(1, 8 * 24 * 60):
            t = now + timedelta(minutes=i)
            # minute
            if minute != "*" and not _cron_match(minute, t.minute):
                continue
            if hour != "*" and not _cron_match(hour, t.hour):
                continue
            if dom != "*" and not _cron_match(dom, t.day):
                continue
            if month != "*" and not _cron_match(month, t.month):
                continue
            # dow: cron uses 0=Sunday, python datetime.weekday() returns 0=Monday.
            if dow != "*":
                py_dow = (t.weekday() + 1) % 7  # 0=Sun
                if not _cron_match(dow, py_dow):
                    continue
            return t.strftime("%a %Y-%m-%d %H:%M GST")
        return "—"
    except Exception:
        return "—"


def _cron_match(field: str, value: int) -> bool:
    """Match a single cron field (minute/hour/etc.) against a value.
    Supports lists (a,b,c), ranges (a-b), steps (*/n or a-b/n), and stars."""
    for part in field.split(","):
        part = part.strip()
        if part == "*":
            return True
        if "/" in part:
            range_part, step_s = part.split("/")
            step = int(step_s)
            if range_part == "*":
                lo, hi = 0, 59
            elif "-" in range_part:
                lo, hi = [int(x) for x in range_part.split("-")]
            else:
                lo = int(range_part)
                hi = 59
            if lo <= value <= hi and (value - lo) % step == 0:
                return True
        elif "-" in part:
            lo, hi = [int(x) for x in part.split("-")]
            if lo <= value <= hi:
                return True
        else:
            if int(part) == value:
                return True
    return False


def _vix_latest() -> dict:
    """Best-effort VIX read via yfinance. Cached for 1h via a sidecar JSON."""
    cache = ROOT / "data_cache" / "_vix_cache.json"
    try:
        if cache.exists():
            c = json.loads(cache.read_text(encoding="utf-8"))
            ts = datetime.fromisoformat(c["ts"])
            if (datetime.now(timezone.utc) - ts).total_seconds() < 3600:
                return c
    except Exception:
        pass
    out = {"ts": datetime.now(timezone.utc).isoformat(timespec="seconds"),
           "value": None, "regime": "unknown"}
    try:
        import yfinance as yf
        df = yf.download("^VIX", period="5d", interval="1d",
                         auto_adjust=True, progress=False, threads=False)
        if df is not None and len(df):
            v = float(df["Close"].iloc[-1])
            out["value"] = round(v, 2)
            if v < 15: out["regime"] = "Bull-Calm"
            elif v < 20: out["regime"] = "Bull-Normal"
            elif v < 25: out["regime"] = "Neutral"
            elif v < 30: out["regime"] = "Elevated"
            elif v < 35: out["regime"] = "High Vol"
            elif v < 40: out["regime"] = "Crisis A"
            else: out["regime"] = "Crisis B HALT"
    except Exception as e:
        out["error"] = str(e)
    try:
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(json.dumps(out), encoding="utf-8")
    except Exception:
        pass
    return out


# ---- CSS + JS -------------------------------------------------------------

CSS = """
:root { color-scheme: dark; --bg:#060a14; --cd:#0d1525; --nv:#1B2A4A;
        --bd:#1a2744; --gold:#C9A84C; --gn:#10B981; --rd:#EF4444;
        --or:#F59E0B; --bl:#2E5FA3; --tl:#1A7A6E;
        --t1:#F1F5F9; --t2:#94A3B8; --t3:#475569; }
* { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
       background: var(--bg); color: var(--t1); margin: 0;
       line-height: 1.45; font-size: 13px; }
h1, h2, h3 { margin: 0; }
a { color: #5aa9ff; text-decoration: none; }
a:hover { text-decoration: underline; }

.header { background: linear-gradient(135deg, var(--nv), #0b1020);
          border-bottom: 2px solid #C9A84C33; padding: 12px 20px;
          position: sticky; top: 0; z-index: 100; backdrop-filter: blur(8px); }
.header-row { display: flex; justify-content: space-between; align-items: center;
              flex-wrap: wrap; gap: 12px; max-width: 1280px; margin: 0 auto; }
.brand { font-size: 18px; font-weight: 900; }
.brand .ar { font-size: 11px; color: var(--gold); margin-left: 8px; }
.brand-sub { font-size: 9px; color: var(--t3); }
.right-tools { display: flex; gap: 10px; align-items: center; }
.search-box { background: #060a14cc; border: 1px solid var(--bd);
              border-radius: 6px; padding: 5px 10px; color: var(--t1);
              font-size: 12px; width: 200px; outline: none; }
.search-box:focus { border-color: var(--gold); }
.bell { position: relative; cursor: pointer; padding: 4px 8px;
        border-radius: 6px; background: #060a14aa; border: 1px solid var(--bd); }
.bell-count { position: absolute; top: -4px; right: -4px;
              background: var(--rd); color: #fff; font-size: 9px;
              font-weight: 800; border-radius: 9px; padding: 1px 5px; }
.nav-pill { padding: 4px 10px; background: #C9A84C20; border-radius: 8px;
            border: 1px solid #C9A84C44; text-align: right; }
.nav-pill .label { font-size: 8px; color: var(--gold); font-weight: 700; }
.nav-pill .val { font-size: 11px; font-weight: 900; color: var(--gold); }
.nav-display .label { font-size: 8px; color: var(--t3); }
.nav-display .val { font-size: 18px; font-weight: 900; color: var(--gold); }

.tab-bar { display: flex; overflow-x: auto; background: var(--cd);
           border-bottom: 1px solid var(--bd); padding: 0 20px;
           position: sticky; top: 64px; z-index: 99; }
.tab-bar-inner { display: flex; max-width: 1280px; margin: 0 auto; width: 100%; }
.tab { padding: 10px 14px; background: none; border: none;
       border-bottom: 2px solid transparent; color: var(--t3);
       font-size: 12px; font-weight: 700; cursor: pointer;
       white-space: nowrap; transition: color .15s, border-color .15s; }
.tab:hover { color: var(--t2); }
.tab.active { border-bottom-color: var(--gold); color: var(--gold); }
.tab-count { display: inline-block; padding: 1px 5px; margin-left: 4px;
             font-size: 9px; font-weight: 800; border-radius: 8px;
             background: #ffffff15; }

.wrap { padding: 16px 20px; max-width: 1280px; margin: 0 auto; }
.tab-panel { display: none; }
.tab-panel.active { display: block; }

.section { background: var(--cd); border: 1px solid var(--bd);
           border-radius: 12px; padding: 14px 16px; margin-bottom: 12px; }
.section.glow { border-color: #C9A84C44; box-shadow: 0 0 24px #C9A84C0a; }
.section h3 { font-size: 14px; font-weight: 800; margin-bottom: 10px;
              display: flex; align-items: center; gap: 8px; }

.badge { display: inline-block; padding: 2px 8px; border-radius: 10px;
         font-size: 9px; font-weight: 800; text-transform: uppercase;
         letter-spacing: .04em; }
.badge.gn { background: #10B98122; color: #10B981; border: 1px solid #10B98144; }
.badge.rd { background: #EF444422; color: #EF4444; border: 1px solid #EF444444; }
.badge.or { background: #F59E0B22; color: #F59E0B; border: 1px solid #F59E0B44; }
.badge.bl { background: #2E5FA322; color: #2E5FA3; border: 1px solid #2E5FA344; }
.badge.gd { background: #C9A84C22; color: #C9A84C; border: 1px solid #C9A84C44; }
.badge.gy { background: #47556922; color: #94A3B8; border: 1px solid #47556944; }

.bar { width: 100%; background: var(--bd); border-radius: 999px; height: 6px;
       overflow: hidden; }
.bar-fill { height: 100%; border-radius: 999px;
            background: linear-gradient(90deg, var(--gn), #22d3ee); }
.bar-fill.gold { background: linear-gradient(90deg, var(--gold), #f59e0b); }
.bar-fill.rd   { background: linear-gradient(90deg, #f87171, var(--rd)); }

.grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
.grid-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
.grid-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
@media (max-width: 960px) {
  .grid-2, .grid-3, .grid-4 { grid-template-columns: 1fr; }
  .search-box { width: 140px; }
}

table { width: 100%; border-collapse: collapse; font-size: 12px; }
th { text-align: left; color: var(--t3); font-weight: 600; font-size: 10px;
     text-transform: uppercase; letter-spacing: .06em; padding: 8px 8px;
     border-bottom: 1px solid var(--bd); }
td { padding: 8px; border-bottom: 1px solid #161e36; }
tr:last-child td { border-bottom: none; }
.mono { font-family: 'SF Mono', Menlo, Consolas, monospace; font-size: 11px; }
.muted { color: var(--t2); font-size: 11px; }

/* Status dots */
.dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%;
       margin-right: 6px; vertical-align: middle; }
.dot.on { background: var(--gn); box-shadow: 0 0 8px var(--gn); }
.dot.off { background: var(--rd); }
.dot.warn { background: var(--or); }

/* KPI / metric tiles */
.tile { background: var(--bg); border-radius: 8px; padding: 10px 12px;
        border: 1px solid var(--bd); }
.tile-label { font-size: 10px; color: var(--t3); text-transform: uppercase;
              letter-spacing: .04em; }
.tile-value { font-size: 22px; font-weight: 800; margin-top: 4px; }
.tile-sub { font-size: 10px; color: var(--t2); margin-top: 2px; }

/* Sprint row */
.sprint-row { display: flex; gap: 10px; padding: 8px 0;
              border-bottom: 1px solid var(--bd); align-items: flex-start; }
.sprint-id { width: 26px; height: 26px; border-radius: 13px; flex-shrink: 0;
             display: flex; align-items: center; justify-content: center;
             font-size: 12px; font-weight: 800; }
.sprint-id.done { background: #10B98122; color: var(--gn); }
.sprint-id.active { background: #C9A84C22; color: var(--gold); }
.sprint-id.pending { background: #47556922; color: var(--t3); }

/* Pipeline flow */
.flow { display: flex; align-items: center; gap: 0; overflow-x: auto;
        padding: 12px 4px; }
.flow-node { background: var(--bg); border: 1px solid var(--bd);
             border-radius: 8px; padding: 8px 12px; min-width: 100px;
             text-align: center; flex-shrink: 0; }
.flow-node.active { border-color: var(--gold); box-shadow: 0 0 10px #C9A84C40; }
.flow-node-label { font-size: 9px; color: var(--t3); text-transform: uppercase; }
.flow-node-value { font-size: 14px; font-weight: 800; margin-top: 2px; }
.flow-arrow { color: var(--t3); font-size: 16px; margin: 0 6px; flex-shrink: 0; }

/* Countdown */
.countdown { display: flex; flex-direction: column; padding: 10px 12px;
             background: #1B2A4A55; border-radius: 8px;
             border-left: 3px solid var(--gold); }
.countdown-label { font-size: 9px; color: var(--gold); font-weight: 700;
                   text-transform: uppercase; letter-spacing: .04em; }
.countdown-time { font-family: 'SF Mono', Menlo, monospace; font-size: 13px;
                  font-weight: 800; margin-top: 2px; }
.countdown-event { font-size: 10px; color: var(--t2); margin-top: 2px; }

/* VIX gauge */
.gauge { position: relative; width: 200px; height: 110px; margin: 8px auto; }
.gauge-bg { position: absolute; inset: 0; border-radius: 200px 200px 0 0 / 110px 110px 0 0;
            background: conic-gradient(from 270deg at 50% 100%,
              #10B981 0deg, #C9A84C 50deg, #F59E0B 100deg, #EF4444 180deg);
            -webkit-mask: radial-gradient(circle at 50% 100%, transparent 56px, #000 57px); }
.gauge-needle { position: absolute; bottom: 0; left: 50%; width: 2px;
                height: 100px; background: var(--t1); transform-origin: bottom;
                transition: transform 1s; }
.gauge-label { position: absolute; bottom: -30px; left: 0; right: 0;
               text-align: center; font-size: 14px; font-weight: 800;
               color: var(--gold); }
.gauge-regime { position: absolute; bottom: -50px; left: 0; right: 0;
                text-align: center; font-size: 10px; color: var(--t2); }

/* Equity chart */
.eq-chart-svg { width: 100%; height: 200px; background: var(--bg);
                border-radius: 8px; border: 1px solid var(--bd); }

/* Telegram log entry */
.tg-entry { padding: 8px 10px; border-bottom: 1px solid var(--bd);
            display: flex; gap: 10px; align-items: flex-start; }
.tg-entry .ts { font-family: 'SF Mono', Menlo, monospace; font-size: 10px;
                color: var(--t3); flex-shrink: 0; width: 130px; }
.tg-entry .body { flex: 1; font-size: 11px; color: var(--t2); }

/* Commit row */
.commit-row { display: grid; grid-template-columns: 90px 130px 1fr;
              gap: 12px; padding: 8px 0; border-bottom: 1px solid var(--bd);
              font-size: 11px; align-items: center; }
.commit-row .sha { font-family: 'SF Mono', Menlo, monospace; color: var(--gold);
                   font-weight: 700; }

/* History entry */
.history-row { padding: 10px 0; border-bottom: 1px solid var(--bd); }
.history-row .date { font-size: 11px; color: var(--gold); font-weight: 700;
                     margin-bottom: 4px; }
.history-row ul { margin: 4px 0 0 0; padding-left: 18px; }
.history-row li { font-size: 11px; margin: 2px 0; color: var(--t2); }

/* Footer */
.footer { padding: 14px 20px; max-width: 1280px; margin: 0 auto;
          border-top: 1px solid var(--bd); color: var(--t3); font-size: 10px;
          margin-top: 24px; }

/* Hidden by search */
.search-hidden { display: none !important; }
"""


JS = """
(function() {
  // ----- TABS -----
  function setTab(id) {
    document.querySelectorAll('.tab').forEach(t => {
      t.classList.toggle('active', t.dataset.tab === id);
    });
    document.querySelectorAll('.tab-panel').forEach(p => {
      p.classList.toggle('active', p.id === 'panel-' + id);
    });
    try { localStorage.setItem('aig_tab', id); } catch (e) {}
    applySearch();
  }
  document.querySelectorAll('.tab').forEach(t => {
    t.addEventListener('click', () => setTab(t.dataset.tab));
  });
  try {
    const saved = localStorage.getItem('aig_tab');
    if (saved && document.getElementById('panel-' + saved)) setTab(saved);
  } catch (e) {}

  // ----- GLOBAL SEARCH -----
  function applySearch() {
    const q = (document.getElementById('global-search').value || '').trim().toLowerCase();
    const panel = document.querySelector('.tab-panel.active');
    if (!panel) return;
    // search-scope items are .section + their descendants
    panel.querySelectorAll('[data-search]').forEach(el => {
      if (!q) { el.classList.remove('search-hidden'); return; }
      const haystack = (el.dataset.search || el.textContent).toLowerCase();
      el.classList.toggle('search-hidden', !haystack.includes(q));
    });
  }
  const search = document.getElementById('global-search');
  if (search) {
    search.addEventListener('input', applySearch);
    search.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') { search.value = ''; applySearch(); }
    });
  }

  // ----- ALERT BELL -----
  // count is server-injected as data-count on .bell — toggle dropdown
  const bell = document.getElementById('alert-bell');
  const bellDrop = document.getElementById('alert-drop');
  if (bell && bellDrop) {
    bell.addEventListener('click', (e) => {
      e.stopPropagation();
      bellDrop.style.display = bellDrop.style.display === 'block' ? 'none' : 'block';
    });
    document.addEventListener('click', () => { bellDrop.style.display = 'none'; });
  }

  // ----- COUNTDOWN UPDATER -----
  function pad(n) { return String(n).padStart(2, '0'); }
  function tick() {
    document.querySelectorAll('[data-target-ts]').forEach(el => {
      const t = parseInt(el.dataset.targetTs, 10);
      if (!t) return;
      const now = Math.floor(Date.now() / 1000);
      let diff = t - now;
      if (diff < 0) { el.textContent = 'now / past'; return; }
      const d = Math.floor(diff / 86400); diff -= d * 86400;
      const h = Math.floor(diff / 3600); diff -= h * 3600;
      const m = Math.floor(diff / 60); diff -= m * 60;
      const s = diff;
      let parts = [];
      if (d) parts.push(d + 'd');
      parts.push(pad(h) + ':' + pad(m) + ':' + pad(s));
      el.textContent = parts.join(' ');
    });
  }
  tick();
  setInterval(tick, 1000);

  // ----- HISTORY FILTER -----
  const histFilter = document.getElementById('history-filter');
  if (histFilter) {
    histFilter.addEventListener('input', () => {
      const q = histFilter.value.trim().toLowerCase();
      document.querySelectorAll('#panel-history [data-search]').forEach(el => {
        const hay = (el.dataset.search || el.textContent).toLowerCase();
        el.classList.toggle('search-hidden', q && !hay.includes(q));
      });
    });
  }

  // ----- CEO DECISION FILTER -----
  const ceoFilter = document.getElementById('ceo-filter');
  if (ceoFilter) {
    ceoFilter.addEventListener('input', () => {
      const q = ceoFilter.value.trim().toLowerCase();
      document.querySelectorAll('#panel-ceo [data-search]').forEach(el => {
        const hay = (el.dataset.search || el.textContent).toLowerCase();
        el.classList.toggle('search-hidden', q && !hay.includes(q));
      });
    });
  }
})();
"""


# ---- tab renderers --------------------------------------------------------

def _status_class(s: str) -> str:
    s = (s or "").lower()
    if any(k in s for k in ("done", "pass", "cleared", "resolved", "alive", "online")):
        return "gn"
    if any(k in s for k in ("warn", "near", "noted", "active", "in progress", "iterating", "scheduled")):
        return "or"
    if any(k in s for k in ("fail", "blocking", "down", "error")):
        return "rd"
    if any(k in s for k in ("pending", "waiting", "queued", "—")):
        return "gy"
    return "bl"


def _render_overview(state):
    runs = state["runs"]
    sprint = state["brain"]["sprint_tracker"]
    sprint_done = sum(1 for r in sprint if "DONE" in r["status"] or "✅" in r["status"])
    universes = state["universes"]
    paper = state["paper"] or {}
    open_positions = paper.get("open_positions", {}) if paper else {}
    history = paper.get("history", []) if paper else []

    # Sprint rows
    sprint_rows = []
    for r in sprint:
        status = r["status"]
        is_done = "DONE" in status or "✅" in status
        is_active = "IN PROGRESS" in status or "🔄" in status
        cls = "done" if is_done else ("active" if is_active else "pending")
        bcls = "gn" if is_done else ("or" if is_active else "gy")
        glyph = "✓" if is_done else r["id"]
        sprint_rows.append(f"""
        <div class="sprint-row" data-search="{esc(r['item'] + ' ' + r['status'] + ' ' + r['notes'])}">
          <div class="sprint-id {cls}">{esc(glyph)}</div>
          <div style="flex:1;">
            <div style="font-weight:700;">{esc(r['item'])}</div>
            <div class="muted">{esc(r['notes'][:140])}</div>
          </div>
          <span class="badge {bcls}">{esc(status.strip())}</span>
        </div>""")

    # Signal Pipeline
    portfolio_cleared = [k for k, v in runs.items() if v["passed"]]
    paper_open = len(open_positions)
    paper_closed = len(history)
    pipeline = f"""
    <div class="flow">
      <div class="flow-node">
        <div class="flow-node-label">Data</div>
        <div class="flow-node-value">{universes['US halal'][0] + universes['UAE halal'][0] + universes['Crypto halal'][0]:,}</div>
        <div class="muted">tickers</div>
      </div>
      <div class="flow-arrow">→</div>
      <div class="flow-node">
        <div class="flow-node-label">Strategies</div>
        <div class="flow-node-value">2</div>
        <div class="muted">EMA-200, Div</div>
      </div>
      <div class="flow-arrow">→</div>
      <div class="flow-node {'active' if portfolio_cleared else ''}">
        <div class="flow-node-label">Gate Pass</div>
        <div class="flow-node-value">{len(portfolio_cleared)}/{len(runs)}</div>
        <div class="muted">portfolios</div>
      </div>
      <div class="flow-arrow">→</div>
      <div class="flow-node {'active' if paper else ''}">
        <div class="flow-node-label">Paper-fwd</div>
        <div class="flow-node-value">{paper_open}</div>
        <div class="muted">{paper_closed} closed</div>
      </div>
      <div class="flow-arrow">→</div>
      <div class="flow-node">
        <div class="flow-node-label">Telegram</div>
        <div class="flow-node-value">{state['telegram_sends']}</div>
        <div class="muted">sent</div>
      </div>
    </div>"""

    # Countdowns
    now_utc = datetime.now(timezone.utc)
    cd_blocks = []
    for t in state["tasks"]:
        if t.get("enabled") == "false":
            continue
        # use stored next_run if available
        next_run = t.get("next_run_iso")
        if next_run:
            try:
                tgt = datetime.fromisoformat(next_run.replace("Z", "+00:00"))
                ts = int(tgt.timestamp())
            except Exception:
                ts = 0
        else:
            ts = 0
        cd_blocks.append(f"""
        <div class="countdown" data-search="{esc(t['name'])}">
          <div class="countdown-label">{esc(t['name'])}</div>
          <div class="countdown-time" data-target-ts="{ts}">—</div>
          <div class="countdown-event">{esc(t.get('cron','—'))}</div>
        </div>""")

    # Decision Log (last 10)
    dec_html = ""
    for d in state["brain"]["decisions"][-10:][::-1]:
        dec_html += f"""
        <div data-search="{esc(d['id_date'] + ' ' + d['title'])}" style="padding:6px 0; border-bottom:1px solid var(--bd);">
          <div style="font-size:10px; color:var(--gold); font-weight:700;">{esc(d['id_date'])}</div>
          <div style="font-size:11px; color:var(--t1); font-weight:600; margin-top:2px;">{esc(d['title'])}</div>
          <div class="muted">{esc(d['rationale_head'][:200])}</div>
        </div>"""
    if not dec_html:
        dec_html = '<div class="muted">No decisions parsed from ceo_brain.md yet.</div>'

    # Circuit Breakers (v7.0 §11)
    cbs = [
        ("Portfolio >8%/day", "Tier 1", "Halt all. No override.", "ARMED"),
        ("Position >15% loss", "Tier 1", "Hard exit. No override.", "ARMED"),
        ("VIX > 40", "Tier 1", "100% cash. Resume when VIX<35.", "ARMED"),
        ("Correlation > 0.85", "Tier 1", "No new entries. Rebalance.", "ARMED"),
        ("Drawdown > 20%", "Tier 1", "100% cash. Full R&D review.", "ARMED"),
        ("All feeds fail", "Tier 1", "Zero trading.", "ARMED"),
        ("Shariah breach", "Tier 1", "Exit non-compliant.", "ARMED"),
        ("Crypto -30%", "Tier 1 (crypto)", "Halt crypto only.", "ARMED"),
        ("Portfolio >5%/day", "Tier 2", "CIO 6-field override.", "ARMED"),
        ("Position -8%", "Tier 2", "CIO override possible.", "ARMED"),
    ]
    cb_html = "<table><thead><tr><th>Trigger</th><th>Tier</th><th>Action</th><th>Status</th></tr></thead><tbody>"
    for trig, tier, action, status in cbs:
        cb_html += f"<tr data-search='{esc(trig + tier + status)}'><td>{esc(trig)}</td><td class='muted'>{esc(tier)}</td><td class='muted'>{esc(action)}</td><td><span class='badge gn'>{esc(status)}</span></td></tr>"
    cb_html += "</tbody></table>"

    # Audit findings
    audit_html = ""
    for f in state["audit"]:
        sv_cls = "rd" if f["severity"] == "BLOCKING" else ("or" if f["severity"] == "WARNING" else "gy")
        audit_html += f"""
        <div style="display:flex; gap:8px; padding:6px 0; border-bottom:1px solid var(--bd); align-items:center;" data-search="{esc(f['title'] + f['severity'])}">
          <span class="badge {sv_cls}">{esc(f['severity'])}</span>
          <div style="flex:1; font-size:11px;">{esc(f['title'])}</div>
          <span class="badge gn">RESOLVED</span>
        </div>"""
    if not audit_html:
        audit_html = '<div class="muted">No audit report on disk.</div>'

    return f"""
    <div id="panel-overview" class="tab-panel active">

      <div class="section glow" data-search="goals targets">
        <h3>🏆 Sprint Tracker — {sprint_done}/8</h3>
        <div class="bar"><div class="bar-fill" style="width:{(sprint_done/8)*100:.0f}%;"></div></div>
        <div style="margin-top:10px;">{''.join(sprint_rows) or '<div class="muted">No tracker rows parsed.</div>'}</div>
      </div>

      <div class="section" data-search="pipeline flow data strategies gate paper telegram">
        <h3>📡 Signal Pipeline</h3>
        {pipeline}
      </div>

      <div class="grid-2">
        <div class="section" data-search="countdown timers next event">
          <h3>⏱ Next Events</h3>
          <div class="grid-2" style="gap:8px;">{''.join(cd_blocks) or '<div class="muted">No active routines.</div>'}</div>
        </div>
        <div class="section" data-search="circuit breakers safety">
          <h3>🛡 Circuit Breakers</h3>
          {cb_html}
        </div>
      </div>

      <div class="grid-2">
        <div class="section" data-search="ceo decisions log">
          <h3>📝 Decision Log (last 10)</h3>
          {dec_html}
        </div>
        <div class="section" data-search="audit findings auditor cowork">
          <h3>🔍 Auditor — Cowork</h3>
          {audit_html}
        </div>
      </div>
    </div>"""


def _render_markets(state):
    runs = state["runs"]
    market_blocks = []
    market_meta = {
        "US": ("🇺🇸", "US Equities", "us_halal_full.txt"),
        "UAE": ("🇦🇪", "UAE Equities", "uae_tickers_full.txt"),
        "CRYPTO": ("₿", "Crypto", "halal_crypto_150_USD.txt"),
    }
    for mkt_key, (emoji, name, uni_file) in market_meta.items():
        uni_count = _count_universe(UNIVERSE_DIR / uni_file)
        # gather all strategies for this market
        rows = [v for (s, m), v in runs.items() if m == mkt_key]
        cleared_any = any(r["passed"] for r in rows)
        if rows:
            best = max(rows, key=lambda r: r["sharpe_def"] or -99)
            trades = best["trades"]
            cov = best["contributors"]
            uni_sz = best["universe_size"]
            sr = best["sharpe_def"]
            ex = best["expectancy"]
            wr = (best["win_rate"] or 0) * 100
        else:
            trades = cov = uni_sz = 0
            sr = ex = wr = 0
        verdict_class = "gn" if cleared_any else "or"
        verdict_text = "GATE PASSED" if cleared_any else ("ITERATING" if rows else "—")
        market_blocks.append(f"""
        <div class="section" data-search="{esc(name + ' ' + mkt_key)}">
          <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
            <h3 style="margin:0;">{emoji} {esc(name)}</h3>
            <span class="badge {verdict_class}">{esc(verdict_text)}</span>
          </div>
          <div class="grid-4" style="margin-bottom:10px;">
            <div class="tile"><div class="tile-label">Universe</div><div class="tile-value">{uni_count:,}</div></div>
            <div class="tile"><div class="tile-label">Best dSharpe</div><div class="tile-value">{sr:.2f}</div></div>
            <div class="tile"><div class="tile-label">Best Exp</div><div class="tile-value">{ex:.2f}</div></div>
            <div class="tile"><div class="tile-label">Best WR</div><div class="tile-value">{wr:.0f}%</div></div>
          </div>
          <div class="muted">Trades {trades:,} · Contributors {cov}/{uni_sz}</div>
        </div>""")
    return f"""
    <div id="panel-markets" class="tab-panel">
      {''.join(market_blocks)}
    </div>"""


def _render_agents(state):
    # 27 agents per v7.0 §25
    agents = [
        ("L0", "CEO", "Autonomous, recursive self-improvement"),
        ("L1", "CIO", "Capital allocation, signal approval"),
        ("L1", "CFO", "Cost control, quality monitoring"),
        ("L2", "RD-A", "Research — strategy registration"),
        ("L2", "RD-B", "Backtest engine"),
        ("L2", "RD-C", "Paper simulator"),
        ("L2", "RD-D", "Approval committee (gate)"),
        ("L3", "EX-A", "Trend (daily+weekly)"),
        ("L3", "EX-B", "Mean reversion (1H+4H)"),
        ("L3", "EX-C", "Factor (weekly)"),
        ("L3", "EX-D", "Portfolio construction + correlation"),
        ("L3", "EX-E", "Fill intake"),
        ("L3", "EX-F", "Crypto (spot, halal)"),
        ("L4", "RI-F", "Risk manager — sizing, loss ladder"),
        ("L4", "RI-G", "Intraday monitor"),
        ("L4", "RI-H", "Shariah compliance"),
        ("L4", "RI-I", "Macro regime"),
        ("L4", "RI-J", "Alt data"),
        ("L4", "RI-K", "Market intel"),
        ("L5", "IN-L", "Systems — feed health"),
        ("L5", "IN-M", "Orchestrator — schedules"),
        ("L5", "IN-N", "Notification — Telegram"),
        ("L5", "IN-O", "Audit trail"),
        ("L6", "LM-P", "Self-learning"),
        ("L6", "LM-Q", "Persistent memory"),
        ("L7", "PR-R", "Performance"),
        ("L7", "PR-S", "Investor relations"),
    ]
    by_layer = {}
    for layer, aid, desc in agents:
        by_layer.setdefault(layer, []).append((aid, desc))
    blocks = []
    for layer in sorted(by_layer.keys()):
        rows = "".join(
            f"<tr data-search='{esc(aid + desc)}'><td class='mono' style='color:var(--gold)'>{esc(aid)}</td><td>{esc(desc)}</td><td><span class='badge gn'>active</span></td></tr>"
            for aid, desc in by_layer[layer]
        )
        blocks.append(f"""
        <div class="section" data-search="layer {esc(layer)}">
          <h3>Layer {esc(layer)}</h3>
          <table>{rows}</table>
        </div>""")
    return f"""<div id="panel-agents" class="tab-panel">{''.join(blocks)}</div>"""


def _render_kpis(state):
    runs = state["runs"]
    universes = state["universes"]
    best_sr = max((v["sharpe_def"] for v in runs.values() if v["sharpe_def"] is not None), default=0)
    pipeline_count = len({s for (s, _) in runs.keys()})
    kpis = [
        ("Annual Return",      "—",                 "≥3x / 10x asp",  "pending", "Paper not started"),
        ("Sharpe (best portfolio)", f"{best_sr:.2f}", "≥1.5",          "pass" if best_sr >= 1.5 else "info", "Deflated under N=6"),
        ("Max Drawdown",       "—",                 "<20%",           "pending", "Paper not started"),
        ("Alpha vs S&P 500",   "—",                 ">0",             "pending", "Paper not started"),
        ("Win Rate ★★★★+",     "—",                 ">50%",           "pending", "Rolling 30 trades"),
        ("Halal Compliance",   "100%",              "100%",           "pass", "Universes pre-screened"),
        ("Max Eq Positions",   "0",                 "8",              "pass", "Paper, no positions"),
        ("Max Crypto Positions", "0",               "3",              "pass", "Paper, no positions"),
        ("Crypto Allocation",  "0%",                "≤10% NAV",       "pass", "—"),
        ("BTC-SPY Correlation","—",                 "alert >0.70",    "pending", "Monitored once positions open"),
        ("Strategy Pipeline",  f"{pipeline_count}", "≥3",             "pass" if pipeline_count >= 3 else "warn", "Need MBV as 3rd"),
        ("Data Uptime",        "~95%",              ">99.5%",         "warn", "UAE yf gap mitigated by TV cache"),
        ("Audit Coverage",     "100%",              "100%",           "pass", "Every run logs to audit_trail.md"),
        ("Notification Latency","<1s",              "<60s",           "pass", "Telegram pushes immediate"),
    ]
    rows = ""
    for n, c, t, s, note in kpis:
        rows += f"<tr data-search='{esc(n + s + note)}'><td><b>{esc(n)}</b></td><td class='mono'>{esc(c)}</td><td class='muted'>{esc(t)}</td><td><span class='badge {_status_class(s)}'>{esc(s)}</span></td><td class='muted'>{esc(note)}</td></tr>"
    return f"""
    <div id="panel-kpis" class="tab-panel">
      <div class="section">
        <h3>🎯 KPI Scorecard (v7.0 §24, 14 KPIs)</h3>
        <table>
          <thead><tr><th>KPI</th><th>Current</th><th>Target</th><th>Status</th><th>Note</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>
      </div>
    </div>"""


def _render_live_status(state):
    tg = state["tg"]
    services = [
        ("Engine (Python+yfinance)", True, f"validation_*.json files present: {len(list(ROOT.glob('validation_*.json')))}"),
        ("TradingView MCP", state.get("tv_ok", True), "Last chart access via dashboard generator"),
        ("Telegram Bot (@AIV_Fund_Bot)", tg["alive"], f"pid={tg['bot_pid']} · policy={tg['policy']} · last log {tg['last_log_mtime'] or '—'}"),
        ("GitHub Backup", bool(state["git_remote"]), state["git_remote"] or "—"),
        ("Paper-Forward Detector", state["paper"] is not None, f"Watch list: {', '.join((state['paper'] or {}).get('watch_list', [])) or '—'}"),
        ("Cloud Routines", len(state["tasks"]) > 0, f"{sum(1 for t in state['tasks'] if t.get('enabled')!='false')} active / {len(state['tasks'])} total"),
        ("Universe Files", all(_count_universe(UNIVERSE_DIR / f) > 0 for f in ["us_halal_full.txt","uae_tickers_full.txt","halal_crypto_150_USD.txt"]),
         f"US {state['universes']['US halal'][0]} · UAE {state['universes']['UAE halal'][0]} · Crypto {state['universes']['Crypto halal'][0]}"),
    ]
    rows = ""
    for name, ok, detail in services:
        dot = "on" if ok else "off"
        st = "online" if ok else "DOWN"
        cls = "gn" if ok else "rd"
        rows += f"<tr data-search='{esc(name + detail)}'><td><span class='dot {dot}'></span><b>{esc(name)}</b></td><td><span class='badge {cls}'>{esc(st)}</span></td><td class='muted'>{esc(detail)}</td></tr>"
    return f"""
    <div id="panel-live" class="tab-panel">
      <div class="section">
        <h3>🟢 Live Service Status</h3>
        <table>
          <thead><tr><th>Service</th><th>State</th><th>Detail</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>
        <div class="muted" style="margin-top:8px;">Status is sampled at dashboard generation time. The sprint routine regenerates every 2h.</div>
      </div>
    </div>"""


def _render_paper_pnl(state):
    paper = state["paper"]
    if not paper:
        body = '<div class="muted">No paper-forward state file yet. Item 2 deployment writes <code>paper_forward_positions.json</code>.</div>'
        return f'<div id="panel-paper" class="tab-panel"><div class="section"><h3>📈 Paper P&L</h3>{body}</div></div>'
    deployed_at = paper.get("deployed_at", "—")
    history = paper.get("history", [])
    open_pos = paper.get("open_positions", {})
    last_run = paper.get("last_run", "—")
    watch = paper.get("watch_list", [])

    total_pnl_pct = sum(t.get("pnl_pct", 0) for t in history)
    nav = 100000 * (1 + total_pnl_pct / 100)
    win_count = sum(1 for t in history if t.get("pnl_pct", 0) > 0)
    wr = (win_count / len(history) * 100) if history else 0

    # Build a tiny SVG equity curve from history (cumulative)
    pts = [(0, 100000.0)]
    cum_pct = 0
    for t in history:
        cum_pct += t.get("pnl_pct", 0)
        pts.append((len(pts), 100000 * (1 + cum_pct / 100)))
    if len(pts) >= 2:
        xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
        xmin, xmax = min(xs), max(xs); ymin, ymax = min(ys), max(ys)
        ymin = min(ymin, 99000); ymax = max(ymax, 101000)
        def sx(x): return 20 + (x - xmin) * (760 / max(1, xmax - xmin))
        def sy(y): return 180 - (y - ymin) * (160 / max(1, ymax - ymin))
        path = "M " + " L ".join(f"{sx(x):.1f},{sy(y):.1f}" for x, y in pts)
        svg = f"""<svg viewBox="0 0 800 200" class="eq-chart-svg">
          <path d="{path}" stroke="#C9A84C" stroke-width="2" fill="none"/>
          <line x1="20" y1="{sy(100000):.1f}" x2="780" y2="{sy(100000):.1f}" stroke="#1a2744" stroke-dasharray="2,4"/>
          <text x="20" y="14" fill="#94A3B8" font-size="10">${ymax:,.0f}</text>
          <text x="20" y="196" fill="#94A3B8" font-size="10">${ymin:,.0f}</text>
        </svg>"""
    else:
        svg = '<div class="muted">No closed trades yet — equity curve pending.</div>'

    open_rows = ""
    for tk, p in open_pos.items():
        open_rows += f"<tr data-search='{esc(tk)}'><td class='mono'>{esc(tk)}</td><td class='mono'>{esc(p.get('entry_date',''))}</td><td class='mono'>${p.get('entry_price',0):.2f}</td><td class='mono'>${p.get('stop_price') or '—'}</td><td>{p.get('rsi_at_entry','—')}</td></tr>"
    if not open_rows:
        open_rows = "<tr><td colspan='5' class='muted'>No open paper positions.</td></tr>"

    hist_rows = ""
    for t in history[::-1][:20]:
        pnl = t.get("pnl_pct", 0)
        cls = "gn" if pnl > 0 else "rd"
        hist_rows += f"<tr data-search='{esc(t.get('ticker',''))}'><td class='mono'>{esc(t.get('ticker',''))}</td><td class='mono'>{esc(t.get('entry_date',''))} → {esc(t.get('exit_date',''))}</td><td class='mono'>${t.get('entry_price',0):.2f} → ${t.get('exit_price',0):.2f}</td><td><span class='badge {cls}'>{pnl:+.2f}%</span></td><td class='muted'>{esc(t.get('exit_reason',''))}</td></tr>"
    if not hist_rows:
        hist_rows = "<tr><td colspan='5' class='muted'>No closed paper trades yet.</td></tr>"

    return f"""
    <div id="panel-paper" class="tab-panel">
      <div class="section glow">
        <h3>📈 Paper Forward — US Divergence Daily</h3>
        <div class="grid-4">
          <div class="tile"><div class="tile-label">NAV (paper)</div><div class="tile-value" style="color:var(--gold)">${nav:,.0f}</div><div class="tile-sub">{total_pnl_pct:+.2f}% since deploy</div></div>
          <div class="tile"><div class="tile-label">Open</div><div class="tile-value">{len(open_pos)}</div></div>
          <div class="tile"><div class="tile-label">Closed</div><div class="tile-value">{len(history)}</div></div>
          <div class="tile"><div class="tile-label">Win Rate</div><div class="tile-value">{wr:.0f}%</div></div>
        </div>
        <div style="margin-top:14px;">{svg}</div>
        <div class="muted" style="margin-top:8px;">Deployed {esc(deployed_at)} · Last detector run {esc(last_run)} · Watch list: {esc(', '.join(watch))}</div>
      </div>

      <div class="section" data-search="open positions">
        <h3>🟢 Open positions</h3>
        <table>
          <thead><tr><th>Ticker</th><th>Entry date</th><th>Entry price</th><th>Stop</th><th>RSI</th></tr></thead>
          <tbody>{open_rows}</tbody>
        </table>
      </div>

      <div class="section" data-search="closed paper trades history">
        <h3>📋 Closed trades (last 20)</h3>
        <table>
          <thead><tr><th>Ticker</th><th>Period</th><th>Price</th><th>P&L</th><th>Reason</th></tr></thead>
          <tbody>{hist_rows}</tbody>
        </table>
      </div>
    </div>"""


def _render_risk(state):
    vix = state["vix"]
    v = vix.get("value")
    regime = vix.get("regime", "unknown")
    # gauge needle angle: 0-50 maps to 0..180 deg.
    if v is None:
        angle = 90
    else:
        angle = max(0, min(180, (v / 50.0) * 180))
    needle_rotation = angle - 90  # gauge starts at -90deg = left
    paper = state["paper"] or {}
    history = paper.get("history", []) if paper else []
    if history:
        cum = 0
        peaks = []
        max_dd = 0
        equity = 100.0
        peak = 100.0
        for t in history:
            equity *= (1 + t.get("pnl_pct", 0) / 100)
            peak = max(peak, equity)
            dd = (equity - peak) / peak * 100
            max_dd = min(max_dd, dd)
        dd_pct = round(max_dd, 2)
    else:
        dd_pct = 0

    return f"""
    <div id="panel-risk" class="tab-panel">
      <div class="grid-2">

        <div class="section" data-search="vix volatility regime">
          <h3>📊 VIX Regime</h3>
          <div class="gauge">
            <div class="gauge-bg"></div>
            <div class="gauge-needle" style="transform: translateX(-50%) rotate({needle_rotation:.1f}deg);"></div>
            <div class="gauge-label">{esc(v if v is not None else '—')}</div>
            <div class="gauge-regime">{esc(regime)}</div>
          </div>
          <div style="margin-top:54px;">
            <table style="font-size:11px;">
              <tr><td><span class="badge gn">VIX&lt;15</span></td><td class="muted">Bull-Calm — 100% Kelly</td></tr>
              <tr><td><span class="badge gn">15-20</span></td><td class="muted">Bull-Normal — 85% Kelly</td></tr>
              <tr><td><span class="badge or">20-25</span></td><td class="muted">Neutral — 70% Kelly</td></tr>
              <tr><td><span class="badge or">25-30</span></td><td class="muted">Elevated — 50% Kelly</td></tr>
              <tr><td><span class="badge rd">30-40</span></td><td class="muted">High Vol → Crisis A</td></tr>
              <tr><td><span class="badge rd">&gt;40</span></td><td class="muted">Crisis B — 100% cash (Tier 1)</td></tr>
            </table>
          </div>
        </div>

        <div class="section" data-search="drawdown paper portfolio risk">
          <h3>📉 Paper Drawdown</h3>
          <div class="tile" style="margin-bottom:10px;">
            <div class="tile-label">Max DD since deploy</div>
            <div class="tile-value" style="color:{'var(--gn)' if dd_pct >= -5 else 'var(--rd)'}">{dd_pct:+.2f}%</div>
            <div class="tile-sub">Tier 1 limit: -20% (no override)</div>
          </div>
          <div class="bar"><div class="bar-fill {'gold' if dd_pct >= -10 else 'rd'}" style="width:{min(100, abs(dd_pct)/20*100):.0f}%;"></div></div>
          <div class="muted" style="margin-top:8px;">Computed from paper_forward_positions.json equity curve.</div>
        </div>

        <div class="section" data-search="correlation correlations btc spy">
          <h3>🔗 Correlation</h3>
          <div class="muted">BTC-SPY correlation will activate when paper positions exist. Alert threshold &gt;0.70 (per v7.0 §10.1). Tier 1 at &gt;0.85.</div>
          <table style="margin-top:10px;">
            <tr><td>BTC vs SPY</td><td class="muted">—</td><td><span class="badge gy">pending</span></td></tr>
            <tr><td>Crypto vs US Eq</td><td class="muted">—</td><td><span class="badge gy">pending</span></td></tr>
            <tr><td>UAE vs US Eq</td><td class="muted">—</td><td><span class="badge gy">pending</span></td></tr>
          </table>
        </div>

        <div class="section" data-search="sizing kelly cap position limits">
          <h3>📏 Sizing limits</h3>
          <table style="font-size:11px;">
            <tr><td>Kelly cap (equity)</td><td class='mono'>1.5%</td></tr>
            <tr><td>Kelly cap (crypto)</td><td class='mono'>0.75%</td></tr>
            <tr><td>Max single (equity)</td><td class='mono'>15% NAV</td></tr>
            <tr><td>Max single (crypto)</td><td class='mono'>5% NAV</td></tr>
            <tr><td>Max equity positions</td><td class='mono'>8</td></tr>
            <tr><td>Max crypto positions</td><td class='mono'>3</td></tr>
            <tr><td>Crypto allocation cap</td><td class='mono'>10% NAV</td></tr>
          </table>
        </div>

      </div>
    </div>"""


def _render_telegram(state):
    sends = state["tg_log"][-100:][::-1]  # most recent first
    rows = ""
    for s in sends:
        ts = s.get("ts_utc", "")
        try:
            d = datetime.fromisoformat(ts.replace("Z","+00:00")).astimezone(GST)
            ts_disp = d.strftime("%Y-%m-%d %H:%M:%S")
        except Exception:
            ts_disp = ts
        kind = s.get("kind", "text")
        ok = s.get("ok")
        cls = "gn" if ok else "rd"
        rows += f"""
        <div class="tg-entry" data-search="{esc(s.get('preview',''))}">
          <div class="ts">{esc(ts_disp)}</div>
          <div class="body">
            <span class="badge {cls}">{esc(kind)}</span>
            <span class="muted">→ {esc(s.get('to',''))}</span>
            <span class="muted">· msg #{esc(s.get('message_id',''))}</span>
            <div style="margin-top:4px; color:var(--t1)">{esc(s.get('preview',''))}</div>
          </div>
        </div>"""
    if not rows:
        rows = '<div class="muted">No Telegram sends logged. Helper logs to telegram_sent_log.json on every send.</div>'
    return f"""
    <div id="panel-telegram" class="tab-panel">
      <div class="section">
        <h3>📱 Telegram send log (latest 100)</h3>
        {rows}
      </div>
    </div>"""


def _render_commits(state):
    commits = state["commits"]
    remote = state["git_remote"]
    rows = ""
    for c in commits:
        try:
            d = datetime.fromisoformat(c["date"]).strftime("%Y-%m-%d %H:%M")
        except Exception:
            d = c["date"]
        sha = c["sha"]
        url = f"{remote}/commit/{c['full_sha']}" if remote else ""
        sha_html = f'<a href="{esc(url)}" target="_blank">{esc(sha)}</a>' if url else esc(sha)
        rows += f"<div class='commit-row' data-search='{esc(sha + c['subject'])}'><div class='sha'>{sha_html}</div><div class='muted mono'>{esc(d)}</div><div>{esc(c['subject'])}</div></div>"
    if not rows:
        rows = '<div class="muted">No commits.</div>'
    return f"""
    <div id="panel-commits" class="tab-panel">
      <div class="section">
        <h3>📜 Commit timeline (last 30)</h3>
        {rows}
        <div class="muted" style="margin-top:10px;">Remote: <a href="{esc(remote)}" target="_blank">{esc(remote)}</a></div>
      </div>
    </div>"""


def _render_history(state):
    # Sessions from ceo_brain + git log groupings
    sessions = [
        ("May 20 · S1", ["Ingested v7.0 docs", "Connected TV MCP", "Built strategy modules", "US top-30: 0/30 (yfinance 1H too short)", "Created ceo_brain.md"]),
        ("May 20 · S2", ["Authoritative 1,603-ticker US extracted", "Portfolio-level gate built", "TV Strategy Tester: 3 CLEAN_EDGE", "Cloud Routines + Telegram configured", "Weekly + Monthly reports delivered"]),
        ("May 20 · S3", ["US Divergence: PORTFOLIO_CLEARED (dSharpe 2.72 → corrected 2.61 under N=6)", "UAE 44 tickers wired via TV-MCP cache", "Crypto 140 valid, gate FAIL", "First validated strategy ever"]),
        ("May 21 · S4", ["Audit 3 BLOCKINGs resolved", "Paper-forward deployed (top 5)", "UAE 44 → 60 retrievable", "Coverage targets all hit", "Mode 1 Sprint activated (2h cadence)", "GitHub auto-commit wired", "Sprint Fire 1: 4/8 done"]),
    ]
    rows = ""
    for date, items in sessions:
        rows += f"<div class='history-row' data-search='{esc(date + ' ' + ' '.join(items))}'><div class='date'>{esc(date)}</div><ul>" + "".join(f"<li>{esc(i)}</li>" for i in items) + "</ul></div>"
    return f"""
    <div id="panel-history" class="tab-panel">
      <div class="section">
        <h3>📜 Session History</h3>
        <input id="history-filter" placeholder="Filter history…" class="search-box" style="width:100%; margin-bottom:12px;">
        {rows}
      </div>
    </div>"""


def _render_glossary(state):
    terms = [
        ("Validation Gate", "Default-FAIL statistical test. OOS, walk-forward, deflated Sharpe, realistic costs, bootstrap CI."),
        ("Deflated Sharpe", "Sharpe with Bailey & López de Prado haircut for multi-testing. AIG uses N=6 trials post-audit."),
        ("Expectancy", "(Avg Win × WR) / (Avg Loss × LR). >1.0 = positive edge."),
        ("Portfolio Gate", "Aggregates all OOS trades in a universe. Multi-test haircut over trial count, not ticker count."),
        ("Paper-Forward", "Live data, no real money. Strategy runs forward; signals logged + delivered via Telegram."),
        ("Pre-Registration", "Strategy rules frozen in config.py before any test. config_hash binds spec to verdict."),
        ("Trial Budget", "Explicit table in strategy_register.md listing every (strategy × market × timeframe) the CEO has run. Bounds the multi-test haircut."),
        ("Circuit Breaker", "Tier 1 = no override (CEO/CIO cannot bypass). Tier 2 = CIO 6-field override."),
        ("Shariah Screen", "5-point AAOIFI check on every signal. Hardwired; cannot be disabled."),
        ("Mode 1 / Sprint", "Sprint until all 8 targets met. Routine every 2h. No live signals until verified."),
        ("Mode 2 / Steady State", "UAE 10AM GST, US 5:30PM GST signals. Monthly auditor cycle. Continuous improvement."),
        ("ceo_brain.md", "Persistent CEO memory. Read at start of every session. Updated at end."),
        ("Audit (Cowork)", "Independent read-only auditor. Cannot block deployment but flags BLOCKING/WARNING/NOTE."),
    ]
    rows = ""
    for t, d in terms:
        rows += f"<div data-search='{esc(t + d)}' style='padding:8px 0; border-bottom:1px solid var(--bd);'><div style='font-weight:700; color:var(--gold);'>{esc(t)}</div><div class='muted'>{esc(d)}</div></div>"
    return f"""
    <div id="panel-glossary" class="tab-panel">
      <div class="section">
        <h3>📖 Glossary</h3>
        {rows}
      </div>
    </div>"""


def _render_ceo(state):
    decisions = state["brain"]["decisions"]
    rows = ""
    for d in decisions[::-1]:
        rows += f"""
        <div data-search="{esc(d['id_date'] + ' ' + d['title'] + ' ' + d['rationale_head'])}" style="padding:10px 0; border-bottom:1px solid var(--bd);">
          <div style="display:flex; gap:8px; align-items:center;">
            <span class="badge gd mono">{esc(d['id_date'])}</span>
            <span style="font-weight:700; color:var(--t1)">{esc(d['title'])}</span>
          </div>
          <div class="muted" style="margin-top:4px;">{esc(d['rationale_head'])}</div>
        </div>"""
    if not rows:
        rows = '<div class="muted">No decisions logged yet.</div>'
    return f"""
    <div id="panel-ceo" class="tab-panel">
      <div class="section">
        <h3>💬 CEO Decisions — all-time (with reasoning)</h3>
        <input id="ceo-filter" placeholder="Search decisions…" class="search-box" style="width:100%; margin-bottom:12px;">
        {rows}
      </div>
    </div>"""


# ---- main render ----------------------------------------------------------

def render() -> str:
    now_gst = datetime.now(GST).strftime("%Y-%m-%d %H:%M GST")
    universes = {
        "US halal":     (_count_universe(UNIVERSE_DIR / "us_halal_full.txt"), 100),
        "UAE halal":    (_count_universe(UNIVERSE_DIR / "uae_tickers_full.txt"), 60),
        "Crypto halal": (_count_universe(UNIVERSE_DIR / "halal_crypto_150_USD.txt"), 100),
    }
    runs = _latest_validation_results()
    tasks = _scheduled_tasks()
    # Try to compute next_run_iso for each enabled task
    for t in tasks:
        if t.get("enabled") != "false":
            try:
                t["next_run_iso"] = _cron_next_fire_gst(t.get("cron", ""))
            except Exception:
                t["next_run_iso"] = None
            # convert human time back to ISO for JS countdown
            try:
                # _cron_next_fire_gst returns "Mon 2026-05-21 06:18 GST"
                txt = t["next_run_iso"]
                m = re.search(r"(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2})", txt or "")
                if m:
                    y, mo, da, hr, mi = map(int, m.groups())
                    dt = datetime(y, mo, da, hr, mi, tzinfo=GST)
                    t["next_run_iso"] = dt.isoformat()
            except Exception:
                pass

    tg = _telegram_status()
    tg_log = _telegram_sent_log()
    commits = _git_log(30)
    remote = _git_remote_url()
    brain = _ceo_brain_sections()
    audit = _auditor_findings()
    paper = _paper_state()
    vix = _vix_latest()

    state = {
        "now_gst": now_gst,
        "universes": universes,
        "runs": runs,
        "tasks": tasks,
        "tg": tg,
        "tg_log": tg_log,
        "telegram_sends": len(tg_log),
        "commits": commits,
        "git_remote": remote,
        "brain": brain,
        "audit": audit,
        "paper": paper,
        "vix": vix,
    }

    # Compute alert bell count
    alerts = []
    for s in brain["sprint_tracker"]:
        if "IN PROGRESS" in s["status"] or "🔄" in s["status"]:
            alerts.append(f"Sprint Item {s['id']} active: {s['item'][:60]}")
    if vix.get("value") and vix["value"] > 30:
        alerts.append(f"VIX elevated: {vix['value']} ({vix['regime']})")
    if not tg["alive"]:
        alerts.append("Telegram bot DOWN")

    alert_count = len(alerts)
    alert_items = "".join(f'<div style="padding:6px 0; border-bottom:1px solid var(--bd); font-size:11px;">{esc(a)}</div>' for a in alerts) or '<div class="muted">No alerts.</div>'

    tabs_def = [
        ("overview", "📊", "Overview"),
        ("markets", "🌍", "Markets"),
        ("agents", "🤖", "Agents"),
        ("kpis", "🎯", "KPIs"),
        ("live", "🟢", "Live Status"),
        ("paper", "📈", "Paper P&L"),
        ("risk", "📊", "Risk"),
        ("telegram", "📱", "Telegram"),
        ("commits", "📜", "Commits"),
        ("history", "🗂", "History"),
        ("glossary", "📖", "Glossary"),
        ("ceo", "💬", "CEO"),
    ]
    tab_buttons = "".join(
        f'<button class="tab" data-tab="{tid}">{ti} {tl}</button>'
        for tid, ti, tl in tabs_def
    )

    panels = "".join([
        _render_overview(state),
        _render_markets(state),
        _render_agents(state),
        _render_kpis(state),
        _render_live_status(state),
        _render_paper_pnl(state),
        _render_risk(state),
        _render_telegram(state),
        _render_commits(state),
        _render_history(state),
        _render_glossary(state),
        _render_ceo(state),
    ])

    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta http-equiv="refresh" content="900">
<title>AIG Cockpit v2 — Ahmed Investment Group</title>
<style>{CSS}</style>
</head>
<body>

<div class="header">
  <div class="header-row">
    <div>
      <div class="brand">AHMED INVESTMENT GROUP <span class="ar">مجموعة أحمد للاستثمار</span></div>
      <div class="brand-sub">v7.0 · بسم الله الرحمن الرحيم · refreshed {esc(now_gst)}</div>
    </div>
    <div class="right-tools">
      <input id="global-search" class="search-box" placeholder="Search this tab…" autocomplete="off">
      <div class="bell" id="alert-bell" data-count="{alert_count}">
        🔔
        {f'<span class="bell-count">{alert_count}</span>' if alert_count else ''}
        <div id="alert-drop" style="display:none; position:absolute; right:0; top:36px; background:var(--cd); border:1px solid var(--bd); border-radius:8px; padding:10px; width:320px; box-shadow: 0 8px 32px #00000060; z-index: 200;">
          <div style="font-size:11px; font-weight:700; color:var(--gold); margin-bottom:6px;">Alerts ({alert_count})</div>
          {alert_items}
        </div>
      </div>
      <div class="nav-display">
        <div class="label">NAV (paper)</div>
        <div class="val">$100,000</div>
      </div>
      <div class="nav-pill">
        <div class="label">MODE 1</div>
        <div class="val">FULL SPRINT</div>
      </div>
    </div>
  </div>
</div>

<div class="tab-bar">
  <div class="tab-bar-inner">{tab_buttons}</div>
</div>

<div class="wrap">
  {panels}
</div>

<div class="footer">
  AIG v7.0 · engine + cockpit unified · backup repo <a href="{esc(remote)}" target="_blank">{esc(remote)}</a> ·
  Rule 01 paper · Rule 15 long only · Rule 16 no leverage · بسم الله
</div>

<script>{JS}</script>
</body></html>
"""


def main():
    html_out = render()
    DASHBOARD_PATH.write_text(html_out, encoding="utf-8")
    print(f"Wrote {DASHBOARD_PATH}  ({len(html_out):,} bytes)")


if __name__ == "__main__":
    main()
